version: 2
updates:
  # Check Java dependencies of the server code
  - package-ecosystem: "maven"
    directory: "/webapp"
    ignore:
      - dependency-name: "uk.ac.dur.cosma:libhdfstream"
      - dependency-name: "org.apache.tomcat:*"
        versions: [">=10.0.0"]
      - dependency-name: "org.apache.tomcat.embed:*"
        versions: [">=10.0.0"]
      - dependency-name: "org.junit.jupiter:*"
        versions: [">=6.0.0"]

    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "java"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
