name: Test C API with sanitizer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install compiler toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake pkg-config

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.10"
        channels: conda-forge
        activate-environment: test-env
        use-mamba: true

    - name: Install dependencies with conda
      run: |
        conda install -y -c conda-forge hdf5=1.12 msgpack-c

    - name: Create build directory
      run: mkdir build

    - name: Configure
      run: cmake .. -DBUILD_WEB_APP=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-fsanitize=address -Wall -Wextra -Werror" -DCMAKE_PREFIX_PATH="${CONDA}"
      working-directory: build

    - name: Build
      run: make
      working-directory: build

    - name: Run tests with CTest
      run: ctest --output-on-failure
      working-directory: build
